# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleApp' do
  platform :ios, '11.3'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleApp
  target 'sampleAppTests' do
    inherit! :search_paths
    use_frameworks!
    # Pods for testing
    pod 'Nimble', '~> 8.0'
  end

end

target 'sampleApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sampleApp-tvOS

  target 'sampleApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
